import type { Metadata } from "next";
import Link from "next/link";
import { Icon } from "@/components/icons";
import { PageHero } from "@/components/page-hero";
import { StoreButton } from "@/components/store-button";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = { title: "About", description: "Why Vely exists and how we are building more intentional social discovery for singles and couples.", alternates: { canonical: `${SITE_URL}/about` } };

export default function AboutPage() {
  return <main id="main-content"><PageHero eyebrow="OUR STORY" title="Connection should feel human." description="Vely is creating a more thoughtful way for adults—single or together—to discover people, friendships, and shared experiences."/><section className="section"><div className="shell editorial-grid"><div className="editorial-lead"><span className="eyebrow">WHY VELY</span><h2>We built Vely for the space between strangers and real friends.</h2></div><div className="prose"><p>Meeting people as an adult can be surprisingly difficult. Social circles change, cities feel bigger, and most platforms reward attention instead of intention.</p><p>Vely starts with a simpler idea: help people show up clearly, discover others who fit their vibe, and let mutual interest open the conversation. Singles can connect as themselves. Couples can discover and socialize together.</p><p>We are building from Pune, India, with a focus on respectful discovery, user choice, and practical safety controls.</p></div></div></section><section className="section section--tinted"><div className="shell values-grid">{[["heart","Warmth over noise","Discovery should feel welcoming, not overwhelming."],["compass","Choice at every step","You decide how you appear, what you seek, and who connects."],["shield","Safety in the details","Clear rules and usable controls matter more than vague promises."]].map(([icon,title,text]) => <article className="value-card" key={title}><Icon name={icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="section"><div className="shell about-callout"><div><span className="eyebrow">COME AS YOU ARE</span><h2>Single or together, your social life is yours to shape.</h2><p>Vely gives you the tools. You choose where the connection goes.</p></div><StoreButton location="about"/></div></section><section className="mini-links shell"><Link href="/safety">Read about safety <Icon name="arrow" size={17}/></Link><Link href="/support">Get support <Icon name="arrow" size={17}/></Link></section></main>;
}
