import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { SITE_URL, SUPPORT_EMAIL } from "@/lib/site";

export const metadata: Metadata = { title: "Privacy Policy", description: "How Vely collects, uses, shares, protects, and deletes personal information.", alternates: { canonical: `${SITE_URL}/privacy` } };

export default function PrivacyPage() {
  return <main id="main-content"><LegalPage title="Privacy Policy" description="This policy explains the information Vely handles, why we use it, and the choices available to you.">
    <aside><strong>In short</strong><p>Vely uses account, profile, location, device, interaction, and payment-status information to provide an adults-only social discovery service. We do not sell personal information.</p></aside>
    <h2>1. About Vely</h2><p>Vely is a social discovery application operated by MettaAi from Pune, Maharashtra, India. It helps adults using single or couple profiles discover and communicate with other users. This policy applies to the Vely mobile app and the joinvely.com website.</p>
    <h2>2. Information we collect</h2><h3>Information you provide</h3><ul><li>Email address and authentication information</li><li>Profile type, nickname, age or date of birth, gender, relationship details, interests, biography, and discovery preferences</li><li>Partner profile information when creating a couple profile</li><li>Profile and verification photos you choose to upload</li><li>Messages, reports, support requests, and other content you submit</li></ul><h3>Information collected while using Vely</h3><ul><li>Approximate or precise location, according to your device permission, to support nearby discovery</li><li>Likes, passes, matches, blocks, reports, and feature interactions</li><li>Device, operating system, app version, IP address, diagnostic, security, and crash information</li><li>Subscription status and transaction references supplied by the app store; Vely does not receive your full payment-card details</li></ul>
    <h2>3. How we use information</h2><ul><li>Create and secure accounts, authenticate users, and provide profile functionality</li><li>Power discovery, preferences, matching, messaging, notifications, and subscriptions</li><li>Display profile information to other users according to the product’s visibility rules</li><li>Detect abuse, investigate reports, enforce policies, prevent fraud, and protect users</li><li>Provide support, maintain the service, diagnose problems, and improve features</li><li>Meet legal obligations and respond to lawful requests</li></ul>
    <h2>4. How information is shared</h2><p>Profile information is visible to other Vely users as part of discovery and matching. We also use service providers for hosting, database and authentication, file storage, email delivery, notifications, analytics, and app-store payments. Providers may process information only to deliver their contracted services. We may disclose information when required by law, to protect safety or rights, during a business transaction, or with your direction or consent.</p><p>We do not sell your personal information or use website analytics for advertising profiles.</p>
    <h2>5. Location and profile visibility</h2><p>Location helps Vely identify relevant nearby profiles. The app may display an approximate place or distance rather than exact coordinates. You can change device permissions, although disabling location can limit discovery. Avoid placing addresses or other sensitive details in your public profile.</p>
    <h2>6. Retention and deletion</h2><p>We retain information while your account is active and as needed to provide Vely. After a verified deletion request, the profile is removed from active use and personal information is scheduled for deletion, subject to backups, fraud prevention, dispute resolution, safety, financial, and legal-retention obligations. Some de-identified or aggregated information may remain.</p><p>See <Link href="/delete-account">Delete your account</Link> for request methods and current timelines.</p>
    <h2>7. Your choices</h2><ul><li>Edit profile details and preferences in the app</li><li>Manage camera, photo, notification, and location permissions through device settings</li><li>Block or report users</li><li>Cancel subscriptions through Google Play</li><li>Request access, correction, or deletion by contacting support, subject to applicable law</li></ul>
    <h2>8. Security</h2><p>We use administrative, technical, and organizational safeguards intended to protect information. No internet service can guarantee absolute security. Protect your email account and OTPs, use current software, and tell us promptly about suspected unauthorized access.</p>
    <h2>9. Adults only</h2><p>Vely is intended only for people aged 18 or older. We do not knowingly permit minors to create accounts. Report suspected underage use through the app or our <Link href="/child-safety">child-safety channel</Link>.</p>
    <h2>10. International processing</h2><p>Vely operates from India and uses service providers that may process information in other countries. Privacy protections may differ by location. We use appropriate contractual and operational safeguards where required.</p>
    <h2>11. Website analytics</h2><p>joinvely.com uses privacy-oriented Vercel Web Analytics to measure page views, general device and region information, referrers, and interactions such as Google Play clicks. It does not use third-party advertising cookies. Do not place personal information in website URLs or query parameters.</p>
    <h2>12. Changes and contact</h2><p>We may update this policy as Vely changes. Material changes will be communicated where required, and the date above will be updated. Questions or privacy requests can be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
  </LegalPage></main>;
}
