import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/legal-page";
import { SUPPORT_EMAIL } from "@/lib/site";

export const metadata: Metadata = { title: "Terms of Service", description: "The rules and conditions for accessing and using Vely.", alternates: { canonical: "/terms" } };

export default function TermsPage() {
  return <main id="main-content"><LegalPage title="Terms of Service" description="These terms govern access to and use of the Vely mobile application and related services.">
    <aside><strong>Please read these terms</strong><p>By creating an account or using Vely, you agree to these Terms and our <Link href="/privacy">Privacy Policy</Link>. If you do not agree, do not use the service.</p></aside>
    <h2>1. Eligibility</h2><p>You must be at least 18, legally able to enter a contract, and permitted to use Vely under applicable law. You may not use Vely if your account was previously removed for serious policy violations. We may request information needed to confirm eligibility.</p>
    <h2>2. Your account</h2><p>Provide accurate information, keep your email account secure, never share OTPs, and tell us about unauthorized access. You are responsible for activity through your account. Do not create accounts for another person without authorization or use multiple accounts to evade restrictions.</p>
    <h2>3. Profiles and content</h2><p>Your profile must honestly represent you or, for a couple profile, the participating adults. Only upload content you have the right and consent to use. Profiles and content must not include minors, nudity, explicit sexual material, hate, violence, illegal activity, impersonation, misleading claims, private information about others, spam, or unauthorized commercial promotion.</p><p>You retain ownership of your content. You grant Vely a non-exclusive, worldwide, royalty-free license to host, process, reproduce, adapt for technical display, and show that content only as needed to operate, secure, and improve the service. This license ends when the content is deleted, except for lawful retention and backups.</p>
    <h2>4. Community conduct</h2><p>Do not harass, threaten, stalk, discriminate, defraud, solicit money, distribute malware, scrape data, interfere with the service, or pressure others into contact or meetings. Respect boundaries and consent. Reports made in bad faith or attempts to weaponize safety tools are also prohibited.</p>
    <h2>5. Matches and in-person interactions</h2><p>Vely does not conduct comprehensive background checks and cannot guarantee a person’s identity, statements, intentions, or conduct. Verification signals are limited and are not endorsements. You are responsible for your interactions and decisions. Follow our <Link href="/safety">safety guidance</Link>, meet publicly, and contact local authorities in an emergency.</p>
    <h2>6. Subscriptions and purchases</h2><p>Optional features may be sold through Google Play. Prices, billing periods, benefits, trials, renewal, cancellation, and refund eligibility are shown before purchase and governed by applicable store terms. Subscriptions may renew until cancelled through the store. Deleting Vely does not automatically cancel a store subscription.</p>
    <h2>7. Enforcement</h2><p>We may investigate content and conduct, limit visibility, remove content, suspend features, or terminate accounts to enforce these Terms, protect users, comply with law, or protect the service. Where appropriate, we may preserve information and cooperate with lawful authorities.</p>
    <h2>8. Intellectual property</h2><p>Vely’s software, visual design, name, brand, and non-user content belong to MettaAi or its licensors. These Terms give you a limited, personal, revocable, non-transferable license to use the app. You may not copy, reverse engineer, resell, or create unauthorized derivative services except where law expressly permits.</p>
    <h2>9. Service availability</h2><p>Features may change, experience interruptions, or be discontinued. Vely is provided “as is” and “as available” to the extent permitted by law. We do not promise uninterrupted operation, a particular number of profiles or matches, or any specific social outcome.</p>
    <h2>10. Liability</h2><p>To the maximum extent permitted by law, MettaAi is not liable for indirect, incidental, special, consequential, or punitive losses arising from use of Vely or interactions between users. Nothing here excludes rights or liabilities that cannot lawfully be excluded.</p>
    <h2>11. Termination and deletion</h2><p>You may stop using Vely and request account deletion at any time. See our <Link href="/delete-account">account deletion instructions</Link>. Sections that logically survive termination—including ownership, disclaimers, liability, and dispute provisions—continue to apply.</p>
    <h2>12. Governing law and changes</h2><p>These Terms are governed by the laws of India, subject to mandatory consumer rights and applicable jurisdiction rules. We may update the Terms as the service evolves. Continued use after an effective update constitutes acceptance where permitted.</p>
    <h2>13. Contact</h2><p>Questions about these Terms can be sent to <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.</p>
  </LegalPage></main>;
}
